language: android
dist: precise
sudo: required
jdk:
- oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL=27
  - ANDROID_API_LEVEL_22=22
  - ANDROID_BUILD_TOOLS_VERSION=27
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
  - ANDROID_TARGET=android-26
  - ADB_INSTALL_TIMEOUT=20

android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - tools
  - android-$ANDROID_API_LEVEL
  - addon-google_apis-google-$ANDROID_API_LEVEL
  - extra-google-google_play_services
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - android-sdk-license-.+
  - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL_22
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-preview-license-52d11cd2
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
- chmod +x gradlew
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script: ./gradlew clean :app:assemble
